# TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" gl_cv_header_langinfo_codeset=yes"
# TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" gl_cv_header_langinfo_t_fmt_ampm=yes"
# TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" gl_cv_header_langinfo_altmon=yes"
# TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" gl_cv_header_langinfo_era=yes"
# TERMUX_PKG_EXTRA_CONFIGURE_ARGS+=" gl_cv_func_nl_langinfo_yesexpr_works=yes"
